### Create Product
POST http://localhost:5000/product
Content-Type: application/json

{
  "name": "Xiaomi",
  "description": "Latest Apple phone",
  "price": 999.99,
  "stock": 25,
  "categoryId" : 4
}

### get Products
GET http://localhost:5000/product?sort=-id&categoryId=1&productName=iPho


### get Product
GET http://localhost:5000/product/17


### Update Product
PATCH  http://localhost:5000/product/17
Content-Type: application/json

{
  "name": "Xiaomi1",
  "categoryId" : 1
}

### Update Product Stock
PATCH  http://localhost:5000/product/17/stock
Content-Type: application/json

{
  "stock": 22
}

### Delete Product
DELETE  http://localhost:5000/product/8
Content-Type: application/json

{
  "name": "Xiaomi1",
  "categoryId" : 1
}